function flState = async_fl_update(flState,uav,cycle)

%% Local training simulation

lr=0.01;

signal=uav.dataQuality*0.02;

localModel=uav.flModel + signal*ones(1,10);

%% ===== STALENESS =====

staleness=max(0,...
    flState.globalRound-uav.lastGlobalRound);

stalenessWeight=1/(1+staleness);

%% ===== ENERGY WEIGHT =====

energyWeight=uav.energy/100;

%% ===== DATA QUALITY WEIGHT =====

dataWeight=uav.dataQuality;

%% ===== FINAL WEIGHT =====

finalWeight=...
    stalenessWeight*...
    energyWeight*...
    dataWeight;

%% ===== AGGREGATE =====

if strcmp(uav.type,'RGB')

    flState.globalModelRGB=...
        (1-finalWeight)*...
        flState.globalModelRGB+...
        finalWeight*...
        localModel;

else

    flState.globalModelThermal=...
        (1-finalWeight)*...
        flState.globalModelThermal+...
        finalWeight*...
        localModel;

end

%% ===== UPDATE SERVER =====

flState.globalRound=...
    flState.globalRound+1;

flState.totalAsyncUpdates=...
    flState.totalAsyncUpdates+1;

flState.lastUpdateCycle=cycle;

flState.stalenessHistory(end+1)=...
    staleness;

flState.energyHistory(end+1)=...
    uav.energy;

flState.lossHistory(end+1)=...
    norm(flState.globalModelRGB)+...
    norm(flState.globalModelThermal);

fprintf(['\n[ASYNC FL] UAV %d uploaded | ' ...
    'Energy=%.1f%% | ' ...
    'Staleness=%d | ' ...
    'Weight=%.3f\n'],...
    uav.id,...
    uav.energy,...
    staleness,...
    finalWeight);

end