
clear;
clc;

%% Dataset Path
datasetPath = 'C:\DisasterDataset';

%% Load Dataset
imds = imageDatastore( ...
    datasetPath, ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');

disp(countEachLabel(imds))

%% Split Data
[imdsTrain,imdsValidation] = splitEachLabel( ...
    imds, ...
    0.8, ...
    'randomized');

%% Load ResNet18
net = resnet18;

inputSize = net.Layers(1).InputSize;

%% Resize Images
augTrain = augmentedImageDatastore( ...
    inputSize(1:2), ...
    imdsTrain, ...
    'ColorPreprocessing','gray2rgb');

augValidation = augmentedImageDatastore( ...
    inputSize(1:2), ...
    imdsValidation, ...
    'ColorPreprocessing','gray2rgb'); 

%% Convert Network To Layer Graph
lgraph = layerGraph(net);

%% Number of Classes
numClasses = numel(categories(imds.Labels));

%% Replace Final Layers
newFc = fullyConnectedLayer( ...
    numClasses, ...
    'Name','fc_custom');

newClass = classificationLayer( ...
    'Name','classoutput_custom');

lgraph = replaceLayer( ...
    lgraph, ...
    'fc1000', ...
    newFc);

lgraph = replaceLayer( ...
    lgraph, ...
    'ClassificationLayer_predictions', ...
    newClass);

%% Training Options
options = trainingOptions( ...
    'adam', ...
    'MiniBatchSize',16, ...
    'MaxEpochs',1, ...
    'InitialLearnRate',1e-4, ...
    'Shuffle','every-epoch', ...
    'ValidationData',augValidation, ...
    'ValidationFrequency',50, ...
    'Verbose',true, ...
    'Plots','training-progress');

%% Train
trainedNet = trainNetwork( ...
    augTrain, ...
    lgraph, ...
    options);

%% Save
save('trained_disaster_cnn.mat','trainedNet');

disp('CNN TRAINING COMPLETE');